# Generated by Django 5.0.1 on 2024-01-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=30)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='proreg',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('barname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('license', models.CharField(max_length=2500)),
                ('uname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='userreg',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('phnnumber', models.IntegerField()),
                ('uname', models.CharField(max_length=30)),
            ],
        ),
    ]
