# Generated by Django 5.0.1 on 2024-01-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreg',
            old_name='phnnumber',
            new_name='phn_no',
        ),
        migrations.AddField(
            model_name='proreg',
            name='image',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proreg',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proreg',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
