# Generated by Django 5.0.1 on 2024-01-27 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barapp', '0002_rename_phnnumber_userreg_phn_no_proreg_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proreg',
            name='image',
        ),
    ]
