# Generated by Django 5.0.1 on 2024-01-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barapp', '0003_remove_proreg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='proreg',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
