# Generated by Django 5.0.1 on 2024-01-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barapp', '0004_alter_login_status_alter_proreg_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='proreg',
            name='location',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
