# Generated by Django 5.0.1 on 2024-02-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barapp', '0006_tbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('messege', models.CharField(max_length=300)),
            ],
        ),
    ]
