# Generated by Django 5.0.1 on 2024-02-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barapp', '0008_alter_tbooking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbooking',
            name='date',
            field=models.DateField(default=True),
        ),
        migrations.AlterField(
            model_name='tbooking',
            name='time',
            field=models.TimeField(),
        ),
    ]
