# Generated by Django 5.0.2 on 2024-02-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barapp', '0012_alter_userreg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.IntegerField(primary_key=1, serialize=False),
        ),
        migrations.AlterField(
            model_name='proreg',
            name='id',
            field=models.IntegerField(primary_key=1, serialize=False),
        ),
        migrations.AlterField(
            model_name='tbooking',
            name='id',
            field=models.IntegerField(primary_key=1, serialize=False),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='id',
            field=models.IntegerField(primary_key=1, serialize=False),
        ),
    ]
