# Generated by Django 5.0.2 on 2024-02-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barapp', '0014_rename_messege_feedback_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='drinksadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=50)),
                ('variant', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='foodsadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('detail', models.CharField(max_length=50)),
            ],
        ),
    ]
