# Generated by Django 5.0.2 on 2024-02-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barapp', '0017_drinksaddvod_drinksaddwhis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='action',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proreg',
            name='action',
            field=models.CharField(default=111, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proreg',
            name='license',
            field=models.FileField(upload_to=''),
        ),
    ]
