# Generated by Django 5.0.2 on 2024-02-28 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barapp', '0019_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='uname',
        ),
    ]
