# Generated by Django 5.0.2 on 2024-02-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barapp', '0020_remove_message_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='proreg',
            name='address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proreg',
            name='phone',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proreg',
            name='location',
            field=models.CharField(max_length=20),
        ),
    ]
