# Generated by Django 5.0.2 on 2024-03-02 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barapp', '0021_proreg_address_proreg_phone_alter_proreg_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='message',
            new_name='adminmessage',
        ),
    ]
